version: '3.1'
services:
  mydb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    container_name: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:8080
    depends_on:
      - "mydb"
    container_name: adminer
